-- One-off cleanup: remove historical outbound_clicks generated by staff
-- (admin / super_admin) browsing the public site. Going forward these clicks
-- are skipped at insert time in app/out/route.ts, so this only purges the
-- backlog accumulated before that change. Run once in the Supabase SQL editor.

-- Preview how many rows will be removed (optional, run first):
-- select count(*) as staff_clicks
-- from public.outbound_clicks
-- where user_id in (
--   select user_id from public.user_roles where role in ('admin', 'super_admin')
-- );

delete from public.outbound_clicks
where user_id in (
  select user_id from public.user_roles
  where role in ('admin', 'super_admin')
);
